name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0-278.1.beta

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.8
  cupertino_icons: ^1.0.8
  cloud_firestore: ^4.17.5
  pdf: ^3.11.3
  path_provider: ^2.1.5
  fl_chart: ^1.0.0
  printing: ^5.13.1
  flutter_svg: ^2.0.7
  image_picker: ^1.0.7
  firebase_storage: ^11.6.7
  excel: ^2.1.0
  flutter_riverpod: ^2.5.1
  # Dépendances pour l'intégration avec le backend Node.js
  http: ^1.1.0
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo/
    - assets/png/
    - assets/images/google_logo.png
    - assets/images/logo.png
    - assets/images/management.png
