// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfsx72p8Wdm2UJXDaDlG81adZPAof0AeE',
    appId: '1:782445988462:web:36731f14e614ed1deef47f',
    messagingSenderId: '782445988462',
    projectId: 'api-cm-d2043',
    authDomain: 'api-cm-d2043.firebaseapp.com',
    storageBucket: 'api-cm-d2043.firebasestorage.app',
    measurementId: 'G-YZPW12921V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsH8JRRdORx16vKCZ8LPyMVPe_V87yR6w',
    appId: '1:782445988462:android:c536e1b8a05b9e1eeef47f',
    messagingSenderId: '782445988462',
    projectId: 'api-cm-d2043',
    storageBucket: 'api-cm-d2043.firebasestorage.app',
  );
}
